cv/urls.py
from django.urls import path # type: ignore
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.cv_list, name='cv_list'),
    path('add/', views.cv_add, name='add_cv'),
    path('<int:pk>/edit/', views.cv_edit, name='edit_cv'),
    path('<int:pk>/delete/', views.cv_delete, name='delete_cv'),
   
]

dani_site/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

from django.conf import settings # NEW
from django.conf.urls.static import static # NEW
from django.urls import path, include # type: ignore # Add import for include


urlpatterns = [

    path('', include('pages.urls')),
    path('cv_dani/', include('cv.urls')),
    path('twomodels/', include('twomodels.urls')),  # Include twomodels app URLs
    # Urls for account management
    path('accounts/', include('allauth.urls')), 
    path('accounts/', include('accounts.urls')), # NEW
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py


from django.urls import path  # type: ignore
from . import views


app_name = 'pages'
urlpatterns = [
    # Standalone Web Pages

    path('', views.home, name='home'),
    path('about-me/', views.about, name='about'),
    path('my-services/', views.services, name='services'),
    path('my-contact/', views.contact_view, name='contact'),
  
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web-Developper Site</title>
    	
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-YWznkfwAFCWqRWcckxtBTjafBkmDhqv+bCWznHdITyEvA2PVzCTaNN1tFCl3NJJiHcDlxzYHGIYrGXGkz7A0gw==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
    <link rel="stylesheet" href="/static/css/base.css" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" integrity="sha384-0evNxOUCibvMUYzfcNJzS09vQKdBvliNqZ6LU4uLcofAVaRUjN4z4j1zJJGru7oi" crossorigin="anonymous">
    
</head>
<body>
    <section class="nav-section">
        <nav>
          <a href="{% url 'pages:home' %}"><img src="{% static 'pages/img/web-icon.png' %} " alt=""></a>
          <div class="nav-links" id="navLinks">
            <i class="fa fa-times" onclick="hideMenu()"></i>
            <ul>
              <li><a href="{% url 'pages:home' %}">HOME</a></li>
              <li><a href="{% url 'pages:about' %}">ABOUT-ME</a></li>
              <li><a href="{% url 'pages:services' %}">SERVICES</a></li>
              <li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
              <br>
              <br>
              <li>
                <form action="{% url 'cv:cv_list' %}" method="get">
                  <label for="search_query" class="sr-only"></label>
                  <input type="text" id="search_query" name="search_query"  placlass="form-control-sm" placeholder="CV ">
                  <button type="submit" class="btn btn-sm btn-primary">Search</button>
                </form>
              </li>
              </ul>
          </div>
          <i class="fa fa-bars" onclick="showMenu()"></i>
        </nav>
      </section>
      
      
    {% block 'content' %}
    {% endblock %}

    <!-----------Footer--------->
<footer>

</footer>
    <section class="footer">
      
        <!-- <h4>My Web Site</h4> -->
        <br>
        <br>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
             Quod nulla nihil libero itaque vero porro fugiat inventore 
            quibusdam veritatis, et, <br>deleniti velit exercitationem rerum 
            a distinctio cum nobis recusandae. Deleniti?</p>
        <div class="icons">
            <a href="https://www.facebook.com/Dani Hangi"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-whatsapp"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="https://github.com/DaniHangi/MyWebSite.git">
                <i class="fab fa-github"></i>
            </a>
            
        </div>
        <div class="social-icons">
           
        </div>
        <p>Site Made, Created and Managed by Ir Dani Hangi. Copyright ©2024</p>
        

    </section>

   



    <!-----JavaScript pour le Toggle Menu---->
    

    <script>

        var navLinks = document.getElementById("navLinks");
        
        function showMenu(){
            navLinks.style.right="0";
        }

        function hideMenu(){
            navLinks.style.right="-200px";
        }
    </script>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-OgqUQ10ByIDABHl6fc+/+BQvfbIEiRD5lwLHWsSLLLdCEHrXLSyOB Uw1RCKSX8vQ" crossorigin="anonymous"></script>


                
</body>
</html>