cv/urls.py
from django.urls import path # type: ignore
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.cv_list, name='cv_list'),
    path('add/', views.cv_add, name='add_cv'),
    path('<int:pk>/edit/', views.cv_edit, name='edit_cv'),
    path('<int:pk>/delete/', views.cv_delete, name='delete_cv'),
   
]

dani_site/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

from django.conf import settings # NEW
from django.conf.urls.static import static # NEW
from django.urls import path, include # type: ignore # Add import for include


urlpatterns = [

    path('', include('pages.urls')),
    path('cv_dani/', include('cv.urls')),
    path('twomodels/', include('twomodels.urls')),  # Include twomodels app URLs
    # Urls for account management
    path('accounts/', include('allauth.urls')), 
    path('accounts/', include('accounts.urls')), # NEW
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models # type: ignore

class CV(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    summary = models.TextField()
    skills = models.TextField()
    experience = models.TextField()
    education = models.TextField()
    awards = models.TextField()
    portfolio_link = models.URLField()
    cv_file = models.FileField(upload_to='cvs')  # For storing the PDF file

    def __str__(self):
        return self.name

cv/forms.py
from django import forms 
from .models import CV  # Assuming CV model is in the same app

class CVForm(forms.ModelForm):
    class Meta:
        model = CV
        fields = ['name', 'email', 'skills', 'summary','phone_number', 'portfolio_link', 'cv_file' ]

cv/views.py
from pyexpat.errors import messages
# from urllib import request
from django.shortcuts import render, redirect 
from django.core.exceptions import ObjectDoesNotExist 
import cv
from cv.forms import CVForm 
from .models import CV
from django.contrib.auth.decorators import login_required, permission_required

# Import Pagination Stuff
from django.core.paginator import Paginator


# @permission_required('cv.delete_cv', raise_exception=True)
# def cv_list(request):
#     cv_list = CV.objects.all()

#     #set up pangination
#     p = Paginator(cv_list, 1)
#     page = request.GET.get('page')
#     cvs_pagination = p.get_page(page)
#     return render(request, 'cv/cv_list.html', {'cv_list': cv_list, 'cvs_pagination': cvs_pagination})

@permission_required('cv.delete_cv', raise_exception=True)
def cv_list(request):
    """
    Renders a paginated list of CVs with search functionality.

    - Handles both search and pagination scenarios.
    - Uses efficient filtering with `icontains` for case-insensitive search.
    - Preserves pagination behavior during searches (optional).
    - Provides clear context for better understanding.
    """

    search_query = request.GET.get('q', '')  # Get search query or set to empty string

    if search_query:
        cv_list = CV.objects.filter(Q(name__icontains=search_query) | Q(summary__icontains=search_query)) # type: ignore
    else:
        cv_list = CV.objects.all()  # Retrieve all CVs if no search query

    # Set up pagination
    p = Paginator(cv_list, 1)  # Adjust page size as needed
    page = request.GET.get('page')
    cvs_pagination = p.get_page(page)

    context = {
        'cvs_pagination': cvs_pagination,
        'search_query': search_query,  # Pass search query for template usage
    }

    return render(request, 'cv/cv_list.html', context)


 
def cv_add(request):
    if request.method == 'POST':
        form = CVForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cv:cv_list')
    else:
        form = CVForm()
    context = {'form': form}
    return render(request, 'cv/cv_form.html', context)


@login_required
def cv_edit(request, pk):
    cv = CV.objects.get(pk=pk)
    if request.method == 'POST':
        form = CVForm(request.POST, request.FILES, instance=cv)
        if form.is_valid():
            form.save()
            return redirect('cv:cv_list')
    else:
        form = CVForm(instance=cv)
    context = {'form': form, 'cv': cv}
    return render(request, 'cv/cv_edit.html', context)


def cv_delete(request, pk):
    try:
        cv = CV.objects.get(pk=pk)
        cv.delete()
    except ObjectDoesNotExist:
        message = "CV not found."
        return render(request, 'cv_delete.html', {'error': message})  
    return redirect('cv:cv_list')  # Redirect to CV list view after successful deletion

cv/templates/cv/cv_delete.html
{% block 'content' %}

<h1>Confirm Delete CV</h1>
<br>
<br>
<br>

<p>Are you sure you want to delete the CV for "{{ cv.name }}"?</p>
<form action="{% url 'cv:delete_cv' cv.pk %}" method="POST">

  {% csrf_token %}
  <button type="submit" class="btn btn-danger" href="{% url 'cv:cv_list' %}">Delete</button>
  <!-- <p>
    <a href="{% url 'cv:cv_list' %}" >
            <input type="button" value="No">
        </a>
    </p>
    <p>
        <input type="submit" value="Yes">
    </p> -->
     
</form>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

cv/templates/cv/cv_edit.html
{% extends 'base-template.html' %}
{% load static %}

{% block 'content' %}
<div class="cv-edit-form">
  <h1>Edit cv</h1>
  <br>
  <br>
  <br>

  <form action="{% url 'cv:edit_cv' cv.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Save Changes</button>
    <p>
      <a href="{% url 'cv:cv_list' %}">Back</a>
    </p>
  </form>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

{% endblock %}

cv/templates/cv/cv_form.html
{% extends 'base-template.html' %}
{% load static %}


{% block 'content' %}

<h1>Add CV</h1>
<br>
<br>
<br>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit CV</button>
  
</form>
<p>
  <a href="{% url 'cv:cv_list' %}">Back</a>
</p>
<br>
<br>
<br>
<br>
<br>
<br>
   
{% endblock %}

cv/templates/cv/cv_list.html
{% extends 'base-template.html' %}
{% load static %}

{% block 'content' %}
<div class="cv-list">
  <h1>cvs</h1>
  <hr>
  <br>
  <br>
  <br>
  <p>
    <a href="{% url 'cv:add_cv' %}">
      <button>Add a cv</button>
    </a>
  </p>
  <br>

  <table border>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Summary</Summary></th>
        <th>Download CV</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for cv in cvs_pagination %}
      <tr>
        <td>{{ cv.name }}</td>
        <td>{{ cv.email }}</td>
        <td>{{ cv.summary }}</td>

        {% if cv.cv_file %}
        <td><a href="{{ cv.cv_file.url }}">Download</a></td>
        {% else %}
        <td>No CV file uploaded</td>
        {% endif %}

        <td>
          {% if perms.cv.change_cv %}
          <a href="{% url 'cv:edit_cv' cv.pk %}">Edit</a>
          {% endif %}
        </td>
        <td>
          {% if perms.cv.delete_cv %}
          <a href="{% url 'cv:delete_cv' cv.pk %}">Delete</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <!-- {{ cvs }} -->
  <br>
  <!-- Has previous Page : {{ cvs_pagination.has_previous}}
  <br>
  Has previous Page : {{ cvs_pagination.has_next}}
  <br>
  Current Page : {{ cvs_pagination.number }}
  <br>
  Number of Pages : {{ cvs_pagination.paginator.num_pages}}
  <br> -->
  <hr>

  {% if cvs_pagination.has_previous %}
  <a href="?page=1">&laquo First</a>
  <a href="?page={{ cvs_pagination.previous_page_number }}">Previous</a>
{% endif %}


Page {{ cvs_pagination.number }} of {{ cvs_pagination.paginator.num_pages }}

 
{%if cvs_pagination.has_next %}
  <a href="?page={{ cvs_pagination.next_page_number }}">Next</a>
  <a href="?page={{ cvs_pagination.paginator.num_pages }}">Last &raquo</a>
{% endif %}


  </div>

  <br>
  <br>
  <br>
  <br>

{% endblock %}