cv/urls.py
from django.urls import path # type: ignore
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.cv_list, name='cv_list'),
    path('add/', views.cv_add, name='add_cv'),
    path('<int:pk>/edit/', views.cv_edit, name='edit_cv'),
    path('<int:pk>/delete/', views.cv_delete, name='delete_cv'),
   
]

dani_site/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

from django.conf import settings # NEW
from django.conf.urls.static import static # NEW
from django.urls import path, include # type: ignore # Add import for include


urlpatterns = [

    path('', include('pages.urls')),
    path('cv_dani/', include('cv.urls')),
    path('twomodels/', include('twomodels.urls')),  # Include twomodels app URLs
    # Urls for account management
    path('accounts/', include('allauth.urls')), 
    path('accounts/', include('accounts.urls')), # NEW
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twomodels/urls.py
from django.urls import path
from . import views  # Assuming your views.py is in the same app


app_name = 'twomodels'
urlpatterns = [
    # path('developers/<int:dev_id>/', views.developer_detail, name='developer-detail'),
    # Other URL patterns
    path('developers/<int:dev_id>/', views.developer_detail, name='developer-detail'),  # Use 'developer-detail' name
    path('developers/<int:dev_id>/edit/', views.edit_developer, name='edit-developer'),
]

cv/models.py
from django.db import models # type: ignore

class CV(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    summary = models.TextField()
    skills = models.TextField()
    experience = models.TextField()
    education = models.TextField()
    awards = models.TextField()
    portfolio_link = models.URLField()
    cv_file = models.FileField(upload_to='cvs')  # For storing the PDF file

    def __str__(self):
        return self.name

twomodels/models.py
from django.db import models
# from django.utils import timezone

class Developer(models.Model):
  dev_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=255)
  biography = models.TextField()
  image = models.ImageField(upload_to='dev_images/', null=True, blank=True)
  email = models.EmailField(unique=True)
  phone_number = models.CharField(max_length=20, blank=True)
  website_url = models.URLField(blank=True)

  def __str__(self):
    return self.name

twomodels/forms.py
from django import forms
from .models import Developer

class DeveloperForm(forms.ModelForm):
    class Meta:
        model = Developer
        # fields = '__all__'  # Include all fields by default
        # Or, for more granular control:
        fields = ['name', 'biography', 'image', 'email', 'phone_number', 'website_url']

    def clean_email(self):
        """
        Custom validation for the email field.

        Ensures the email is unique (excluding the current object if editing).
        """
        email = self.cleaned_data['email']
        if Developer.objects.filter(email=email).exists():
            current_object = self.instance.pk if self.instance.pk else None
            if current_object is None or email != Developer.objects.get(pk=current_object).email:
                raise forms.ValidationError('This email address is already in use.')
        return email

twomodels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Developer
from .forms import DeveloperForm
from django.contrib.auth.decorators import login_required

@login_required
def developer_detail(request, dev_id):
    developer = get_object_or_404(Developer, dev_id=dev_id)
    return render(request, 'twomodels/developer_detail.html', {'developer' : developer})
    


@login_required
def edit_developer(request, dev_id):
    developer = get_object_or_404(Developer, dev_id=dev_id)

    if request.method == 'POST':
        form = DeveloperForm(request.POST, instance=developer)  # Pass existing object
        if form.is_valid():
            form.save()
            return redirect('twomodels:developer-detail' ,dev_id=developer.pk)  # Redirect to success page
    else:
        form = DeveloperForm(instance=developer)  # Pre-populate with existing data
    context = {'developer': developer, 'form': form}
    return render(request, 'twomodels/edit_developer.html', context)

twomodels/templates/twomodels/developer_detail.html
{% extends 'base-template.html' %}
{% load static %}

{% block 'content' %}
<div class="developer-details-wrapper">
  <div class="developer-details">
    <div class="developer-info">
      <h1>{{ developer.name }}</h1>
      <hr>
      {% if developer.image %}
      <img src="{{ developer.image.url }}" alt="Man Image" class="developer-image">
      {% endif %}
      <p class="developer-bio">{{ developer.biography }}</p>
    </div>
    <div class="developer-actions">
      {% if perms.cv.change_cv %}
      <h2>Edit Developer Information</h2>
      <a href="{% url 'twomodels:edit-developer' developer.pk %}">Edit developer</a>
      {% endif %}

      {% if developer.phone_number or developer.website_url %}
      <h2>Contact</h2>
      {% if developer.phone_number %}
      <p>Phone: {{ developer.phone_number }}</p>
      {% endif %}
      {% if developer.website_url %}
      <p>Website: <a href="{{ developer.website_url }}">{{ developer.website_url }}</a></p>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

twomodels/templates/twomodels/edit_developer.html
{% extends 'base-template.html' %}
{% load static %}

{% block 'content' %}
<div class="edit-developer-form">
  <h1>Edit Developer Information</h1>
  <br>
  <form action="{% url 'twomodels:edit-developer' developer.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
</div>
{% endblock %}