accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    
    path('profile/', views.user_profile, name='profile'),
    path('create/', views.create_account, name='create'),
    path('profile/change/', views.change_profile, name='change-profile'),
]

cv/urls.py
from django.urls import path # type: ignore
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.cv_list, name='cv_list'),
    path('add/', views.cv_add, name='add_cv'),
    path('<int:pk>/edit/', views.cv_edit, name='edit_cv'),
    path('<int:pk>/delete/', views.cv_delete, name='delete_cv'),
   
]

dani_site/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

from django.conf import settings # NEW
from django.conf.urls.static import static # NEW
from django.urls import path, include # type: ignore # Add import for include


urlpatterns = [

    path('', include('pages.urls')),
    path('cv_dani/', include('cv.urls')),
    path('twomodels/', include('twomodels.urls')),  # Include twomodels app URLs
    # Urls for account management
    path('accounts/', include('allauth.urls')), 
    path('accounts/', include('accounts.urls')), # NEW
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py


from django.urls import path  # type: ignore
from . import views


app_name = 'pages'
urlpatterns = [
    # Standalone Web Pages

    path('', views.home, name='home'),
    path('about-me/', views.about, name='about'),
    path('my-services/', views.services, name='services'),
    path('my-contact/', views.contact_view, name='contact'),
  
]

twomodels/urls.py
from django.urls import path
from . import views  # Assuming your views.py is in the same app


app_name = 'twomodels'
urlpatterns = [
    # path('developers/<int:dev_id>/', views.developer_detail, name='developer-detail'),
    # Other URL patterns
    path('developers/<int:dev_id>/', views.developer_detail, name='developer-detail'),  # Use 'developer-detail' name
    path('developers/<int:dev_id>/edit/', views.edit_developer, name='edit-developer'),
]

pages/templates/pages/about.html
{% extends 'base-template.html' %}
{% load static %}






{% block 'content' %}

    <section class="about-us">
        <h1>ABOUT ME</h1>
        <hr>
        <div class="row">
            <div class="about-col">
                <h2>Hi, I am Dani a Web-Developer.</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel, 
                    ipsum temporibus non repellendus voluptates sunt deserunt aliquam e
                    xplicabo provident quo! Cum laudantium non, neque commodi odit a
                    lias consequatur facilis fuga?</p>
                <!-- <a href="#" id="skills-btn" class="hero-btn">Discover My Skills</a> -->
                <h2>My Skills In Development</h2>
                <br>
                <ul >
                    <li>Development
                      <ul>
                        <li>Python (Django, Flask)</li>
                        <li>JavaScript (React, Node.js)</li>
                        <li>HTML/CSS</li>
                      </ul>
                    </li>
                    <li>Design
                      <ul>
                        <li>UI/UX Design</li>
                        <li>Graphic Design</li>
                      </ul>
                    </li>
                </ul>


                <!-- <div class="blog-right">
                    <h3>Front-End</h3>
                    <div>
                        <span>Theology</span>
                        <span>26</span>
                    </div>
    
                    
    
                    <div>
                        <span>Journalism</span>
                        <span>22</span>
                    </div>
                    <h3>Back-End</h3>
    
                    <div>
                        <span>Commerce</span>
                        <span>28</span>
                    </div>
    
                    <div>
                        <span>Electromecanics</span>
                        <span>29</span>
                    </div>
    
                    
                    
                </div> -->


           <h2>Education</h2>
           <br>
           <h4>2024: Bachelor in computer engineering</h4>
           <p>Christian Bilingual University Of Congo, UCBC</p>

           <h4>2018: Diploma in Mathematics and Physics</h4>
           <p>Kambali Institute, INKA</p>

           <h4>2012: Primary certificate</h4>
           <p>E.P NYUKI</p>

            </div>

            <div class="about-col">

                <img src="{% static 'pages/img/Dani_Portrait.jpg' %} " alt="my-own-picture">

            </div>
        </div>

    </section>

    
{% endblock %}

pages/templates/pages/contact.html
{% extends 'base-template.html' %}
{% load static %}

{% block 'content' %}
<div class="contact-form">
  <br>
  <br>
  <br>
  <br>

  <h1>CONTACT</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send Message</button>
  </form>

  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

{% endblock %}

pages/templates/pages/contactForm.html
<h2>Contact form submission</h2>

<p><b>Name: </b>{{name}}</p>
<p><b>E-mail: </b>{{email}}</p>
<p><b>Message content: </b>{{content}}</p>

pages/templates/pages/home.html
{% extends 'base-template.html' %}
{% load static %}


{% block 'content' %}

    <section class="header">
        
        <div class="text-box">
            <h1>KARIBU! WELCOME! BIENVENU!</h1>
            <hr>
        </div>
        <br>
        <div class="links-log">
            <a href="{% url 'login' %}" class="hero-btn">LOGIN</a>
            <a href="{% url 'accounts:create' %}" class="hero-btn">SIGN UP</a>
        </div>
       
        
        
    </section>
    <section class="div-image-developer">
        <div class="img-div"><img src="{% static 'pages/img/dani.jpg' %} " alt="" ></div>
    </section>

    <!-- {% if user_profile.profile_picture %}
        <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture" style="width: 30px; height: 30px; border-radius: 50%; margin-right: 5px;">
    {% endif %} -->

    
     

     <section class="header">
        

        <div class="text-box">
           
                
            
            
            <p><strong>Dani Hangi</strong><br>Student in Computer Engineering department and Teacher Assistant in L0 FTSI. <br> Currently learning computer engineering at Christian Bilingual University Of Congo in Beni Town, DRC. <br><br> <a href="#">Learn more about my studies at UCBC.</a></p>
        </div>
            
        
    </section>
    

    <section class="cta">
        
        <h1>My Curicculum Vitae In PDF Format</h1>
       
        <br>
        <br>
        <br>
        <a href="{% url 'cv:cv_list' %}" class="hero-btn">-- TO MY CV --</a>
        
    </section>

{% endblock %}


 

pages/templates/pages/service.html
{% extends 'base-template.html' %}
{% load static %}


{% block 'content' %}


    <section class="course">
        <h1>MY SERVICES</h1>
        <hr>
        <br>
        </nav>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt accusamus molestiae deleniti ratione sapiente! Harum fuga ducimus ut fugiat quasi natus quisquam quos suscipit dolorem possimus, commodi excepturi placeat autem!</p>
        



        <div class="row">
            <div class="course-col">

                <!-- {%for dev in developers%}
                {{dev.name}}
                {%endfor%} -->

                
                

                <h3>ZakoApp</h3>
                <hr>
                <!-- <h1>{{developer.name}}</h1>
                <h1>{{developer.dev_id}}</h1> -->
                <img src="{% static 'pages/img/boutique.png' %} " alt="" width="90%">
                <br>
                <br>
                <br>
                <div class="class-pdf"><a href="{% url 'pages:contact' %}">PDF Document</a></div>
                <!-- {{developer.name}} -->
                <hr>
                <br>
                <div class="class-pdf"><a href="{%  url 'twomodels:developer-detail' developer.dev_id %}">My colaborator's profile</a></div>
                <hr>
                
                
            </div>
            
            <div class="course-col">
                <h3>Laloca</h3>
                <hr>
                <!-- <h1>{{developer.name}}</h1>
                <h1>{{developer.dev_id}}</h1> -->
                <img src="{% static 'pages/img/locationmaison.jpg' %} " alt="" width="90%">
                <br>
                <br>
                <br>
                <!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis saepe magni dicta ea consequuntur omnis laborum atque, nesciunt nisi non nam nobis qui aliquid voluptatibus consequatur hic! Error, non dolores?</p> -->
                <div class="class-pdf"><a href="{% url 'pages:contact' %}">PDF Document</a></div>
                <hr>
                <br>
                <div class="class-pdf"><a href="{%  url 'twomodels:developer-detail' developer.dev_id %}">My colaborator's profile</a></div>

                <hr>
            </div>
           
            <div class="course-col">
                <h3>E-Wallet</h3>
                <hr>
                <!-- <h1>{{developer.name}}</h1>
                <h1>{{developer.dev_id}}</h1> -->
                <img src="{% static 'pages/img/wallet.jpg' %} " alt="" width="90%">
                <br>
                <br>
                <br>
                <!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis saepe magni dicta ea consequuntur omnis laborum atque, nesciunt nisi non nam nobis qui aliquid voluptatibus consequatur hic! Error, non dolores?</p> -->
                <div class="class-pdf"><a href="{% url 'pages:contact' %}">PDF Document</a></div>
                <hr>
                <br>
                <div class="class-pdf"><a href="{%  url 'twomodels:developer-detail' developer.dev_id %}">My colaborator's profile</a></div>

                <hr>
            </div>
        </div>

    </section>
    
{% endblock %}